export interface PujaPackage {
  id: string
  name: string
  nameHindi: string
  description: string
  longDescription: string
  price: number
  originalPrice: number
  image: string
  category: string
  itemCount: number
  items: string[]
  duration: string
  bestFor: string[]
  rating: number
  reviews: number
  featured?: boolean
}

export const categories = [
  { id: "havan", name: "Havan & Homam", nameHindi: "हवन एवं होम", icon: "flame" },
  { id: "puja", name: "Daily Puja", nameHindi: "दैनिक पूजा", icon: "sun" },
  { id: "katha", name: "Katha & Paath", nameHindi: "कथा एवं पाठ", icon: "book" },
  { id: "shanti", name: "Shanti Puja", nameHindi: "शांति पूजा", icon: "peace" },
  { id: "festival", name: "Festival Special", nameHindi: "त्योहार विशेष", icon: "sparkles" },
  { id: "jaap", name: "Mantra Jaap", nameHindi: "मंत्र जाप", icon: "repeat" },
]

export const pujaPackages: PujaPackage[] = [
  {
    id: "havan-samagri",
    name: "Havan Samagri Kit",
    nameHindi: "हवन सामग्री किट",
    description: "Complete kit for performing traditional Havan with all sacred materials",
    longDescription: "Our comprehensive Havan Samagri Kit contains everything you need to perform a traditional Hindu fire ritual. Each item is carefully sourced and blessed to ensure the purest spiritual experience. The kit includes premium quality havan samagri, sacred woods, ghee, and all necessary offerings.",
    price: 599,
    originalPrice: 799,
    image: "/images/havan.jpg",
    category: "havan",
    itemCount: 21,
    items: [
      "Havan Samagri (500g)",
      "Mango Wood (Aam ki Lakdi)",
      "Camphor (Kapoor)",
      "Pure Cow Ghee (250ml)",
      "Sandalwood Powder",
      "Dried Coconut",
      "Jau (Barley)",
      "Til (Sesame Seeds)",
      "Guggul",
      "Lobaan",
      "Dhoop Batti",
      "Agarbatti",
      "Cotton Wicks",
      "Roli & Moli",
      "Akshat (Rice)",
      "Supari",
      "Laung (Cloves)",
      "Elaichi (Cardamom)",
      "Naariyal (Coconut)",
      "Paan Leaves",
      "Havan Kund Stand"
    ],
    duration: "1-2 hours",
    bestFor: ["New beginnings", "House warming", "Purification", "Health & prosperity"],
    rating: 4.8,
    reviews: 342,
    featured: true
  },
  {
    id: "satyanarayan-katha",
    name: "Satyanarayan Katha Kit",
    nameHindi: "सत्यनारायण कथा किट",
    description: "Everything needed for Shri Satyanarayan Puja and Katha",
    longDescription: "The Satyanarayan Katha is one of the most popular Hindu rituals performed on Purnima (full moon day). This complete kit includes all items needed for the puja, prasad preparation, and the sacred katha recitation. Ideal for monthly Satyanarayan Puja at home.",
    price: 849,
    originalPrice: 1099,
    image: "/images/satyanarayan.jpg",
    category: "katha",
    itemCount: 28,
    items: [
      "Satyanarayan Katha Book",
      "Kalash with Coconut",
      "Mango Leaves",
      "Red Cloth",
      "Yellow Cloth",
      "Panchamrit Ingredients",
      "Mishri (Sugar Candy)",
      "Banana",
      "Singhara (Water Chestnuts)",
      "Suji (Semolina) for Prasad",
      "Ghee (500ml)",
      "Sugar",
      "Dry Fruits Mix",
      "Chandan (Sandalwood Paste)",
      "Kumkum",
      "Haldi",
      "Agarbatti",
      "Diya & Oil",
      "Cotton Wicks",
      "Flowers (Marigold)",
      "Tulsi Leaves",
      "Akshat",
      "Supari",
      "Paan Leaves",
      "Naariyal",
      "Moli (Sacred Thread)",
      "Roli",
      "Janeu (Sacred Thread)"
    ],
    duration: "2-3 hours",
    bestFor: ["Prosperity", "Family wellbeing", "Monthly ritual", "Wish fulfillment"],
    rating: 4.9,
    reviews: 567,
    featured: true
  },
  {
    id: "rudra-abhishek",
    name: "Rudra Abhishek Kit",
    nameHindi: "रुद्राभिषेक किट",
    description: "Sacred materials for Lord Shiva's Rudrabhishek ceremony",
    longDescription: "Rudra Abhishek is a powerful Vedic ritual dedicated to Lord Shiva. This kit contains all the sacred items required for performing the elaborate abhishek ceremony, including all panchamrit ingredients, bilva leaves, and special offerings for Mahadev.",
    price: 1299,
    originalPrice: 1599,
    image: "/images/rudra-abhishek.jpg",
    category: "havan",
    itemCount: 32,
    items: [
      "Shivling (Brass)",
      "Panchamrit Set",
      "Milk (1L)",
      "Curd",
      "Honey",
      "Ghee",
      "Gangajal",
      "Rose Water",
      "Bilva Leaves (108 pcs)",
      "Dhatura Flowers",
      "Bhang",
      "Sandalwood Paste",
      "Vibhuti",
      "Rudraksha Mala",
      "White Flowers",
      "White Cloth",
      "Janeu",
      "Akshat",
      "Supari",
      "Naariyal",
      "Agarbatti",
      "Dhoop",
      "Camphor",
      "Diya",
      "Cotton Wicks",
      "Oil",
      "Roli & Moli",
      "Sugar",
      "Fruits Offering",
      "Bhaang Seeds",
      "Ash Gourd",
      "Rudra Abhishek Book"
    ],
    duration: "3-4 hours",
    bestFor: ["Removing obstacles", "Health", "Spiritual growth", "Monday ritual"],
    rating: 4.9,
    reviews: 289,
    featured: true
  },
  {
    id: "saraswati-puja",
    name: "Saraswati Puja Kit",
    nameHindi: "सरस्वती पूजा किट",
    description: "Complete puja samagri for Goddess Saraswati worship",
    longDescription: "Dedicated to Goddess Saraswati, the deity of knowledge, music, and arts. This kit is perfect for Basant Panchami celebrations and for students seeking blessings for academic success. Includes special white flowers, books, and musical instruments accessories.",
    price: 699,
    originalPrice: 899,
    image: "/images/saraswati.jpg",
    category: "festival",
    itemCount: 24,
    items: [
      "Saraswati Murti/Photo",
      "White Cloth",
      "Yellow Cloth",
      "White Flowers",
      "Yellow Flowers",
      "Mango Leaves",
      "Kalash",
      "Akshat",
      "Kumkum",
      "Haldi",
      "Chandan",
      "Agarbatti",
      "Dhoop",
      "Camphor",
      "Diya",
      "Cotton Wicks",
      "Ghee",
      "Mishri",
      "Fruits",
      "Pen & Notebook (for offering)",
      "Musical Instrument Accessory",
      "Coconut",
      "Paan Supari",
      "Moli"
    ],
    duration: "1-2 hours",
    bestFor: ["Education", "Arts & music", "Basant Panchami", "Knowledge seekers"],
    rating: 4.7,
    reviews: 423
  },
  {
    id: "tulsi-pujan",
    name: "Tulsi Pujan Kit",
    nameHindi: "तुलसी पूजन किट",
    description: "Sacred items for daily Tulsi worship and Tulsi Vivah",
    longDescription: "Tulsi (Holy Basil) is considered the most sacred plant in Hindu tradition. This kit contains everything needed for daily Tulsi puja as well as the special Tulsi Vivah ceremony performed in Kartik month. Regular Tulsi worship brings peace and prosperity to the household.",
    price: 399,
    originalPrice: 499,
    image: "/images/tulsi.jpg",
    category: "puja",
    itemCount: 18,
    items: [
      "Tulsi Kyara Decoration",
      "Red Cloth",
      "Yellow Cloth",
      "Rangoli Colors",
      "Diyas (5 pcs)",
      "Cotton Wicks",
      "Ghee",
      "Kumkum",
      "Haldi",
      "Chandan",
      "Agarbatti",
      "Dhoop",
      "Camphor",
      "Akshat",
      "Flowers",
      "Moli",
      "Coconut",
      "Gangajal"
    ],
    duration: "30-45 minutes",
    bestFor: ["Daily worship", "Tulsi Vivah", "Household peace", "Kartik month"],
    rating: 4.6,
    reviews: 198
  },
  {
    id: "griha-shanti",
    name: "Griha Shanti Paath Kit",
    nameHindi: "गृह शांति पाठ किट",
    description: "Complete kit for house purification and peace ceremony",
    longDescription: "Griha Shanti Paath is performed to remove negative energies from home and establish peace and harmony. This comprehensive kit includes all materials for Vastu purification, Navagraha shanti, and home blessing rituals. Ideal after moving to a new house.",
    price: 1499,
    originalPrice: 1899,
    image: "/images/griha-shanti.jpg",
    category: "shanti",
    itemCount: 35,
    items: [
      "Navagraha Yantra",
      "Vastu Yantra",
      "Havan Samagri (1kg)",
      "Mango Wood",
      "Ghee (500ml)",
      "Camphor",
      "Loban",
      "Guggul",
      "Sandalwood",
      "9 Types of Grains",
      "9 Types of Cloths",
      "Kalash",
      "Coconut (5 pcs)",
      "Mango Leaves",
      "Gangajal",
      "Rose Water",
      "Akshat (1kg)",
      "Flowers",
      "Agarbatti",
      "Dhoop",
      "Diyas (9 pcs)",
      "Cotton Wicks",
      "Oil",
      "Roli",
      "Moli",
      "Haldi",
      "Kumkum",
      "Chandan",
      "Supari",
      "Paan Leaves",
      "Mishri",
      "Dry Fruits",
      "Fruits",
      "Honey",
      "Curd"
    ],
    duration: "4-5 hours",
    bestFor: ["New home", "Vastu correction", "Family harmony", "Removing negativity"],
    rating: 4.8,
    reviews: 156,
    featured: true
  },
  {
    id: "mahamrityunjaya-jaap",
    name: "Mahamrityunjaya Jaap Kit",
    nameHindi: "महामृत्युंजय जाप किट",
    description: "Sacred items for Mahamrityunjaya Mantra recitation",
    longDescription: "The Mahamrityunjaya Mantra is one of the most powerful mantras for health and longevity. This kit contains all items needed for performing the sacred jaap, including a Rudraksha mala for counting, and special offerings for Lord Shiva who bestows the blessing of victory over death.",
    price: 899,
    originalPrice: 1199,
    image: "/images/mahamrityunjaya.jpg",
    category: "jaap",
    itemCount: 22,
    items: [
      "Rudraksha Mala (108+1)",
      "Shivling",
      "Bilva Leaves",
      "Gangajal",
      "Panchamrit",
      "Milk",
      "Honey",
      "Ghee",
      "Curd",
      "Sugar",
      "White Flowers",
      "White Cloth",
      "Sandalwood Paste",
      "Vibhuti",
      "Agarbatti",
      "Dhoop",
      "Camphor",
      "Diya",
      "Cotton Wicks",
      "Oil",
      "Coconut",
      "Mahamrityunjaya Book"
    ],
    duration: "2-3 hours",
    bestFor: ["Health", "Longevity", "Protection", "Recovery from illness"],
    rating: 4.9,
    reviews: 312
  },
  {
    id: "navgraha-shanti",
    name: "Navgraha Shanti Kit",
    nameHindi: "नवग्रह शांति किट",
    description: "Complete puja materials for all nine planetary deities",
    longDescription: "Navgraha Shanti Puja pacifies all nine planets and removes malefic effects from one's horoscope. This elaborate kit contains specific items for each of the nine planets - Surya, Chandra, Mangal, Budh, Guru, Shukra, Shani, Rahu, and Ketu.",
    price: 1799,
    originalPrice: 2299,
    image: "/images/navgraha.jpg",
    category: "shanti",
    itemCount: 45,
    items: [
      "Navgraha Yantra",
      "9 Different Cloths",
      "9 Types of Grains",
      "9 Types of Flowers",
      "9 Types of Fruits",
      "9 Types of Dhoop",
      "Ruby (for Sun)",
      "Pearl (for Moon)",
      "Red Coral (for Mars)",
      "Emerald (for Mercury)",
      "Yellow Sapphire (for Jupiter)",
      "Diamond/Opal (for Venus)",
      "Blue Sapphire (for Saturn)",
      "Hessonite (for Rahu)",
      "Cat's Eye (for Ketu)",
      "Wheat",
      "Rice",
      "Toor Dal",
      "Moong Dal",
      "Chana Dal",
      "Kidney Beans",
      "Black Sesame",
      "Black Urad",
      "Horse Gram",
      "Ghee",
      "Honey",
      "Milk",
      "Curd",
      "Gangajal",
      "Agarbatti",
      "Camphor",
      "Diyas (9 pcs)",
      "Cotton Wicks",
      "Havan Samagri",
      "Mango Wood",
      "Coconut",
      "Akshat",
      "Kumkum",
      "Haldi",
      "Chandan",
      "Roli",
      "Moli",
      "Supari",
      "Paan",
      "Navgraha Stotra Book"
    ],
    duration: "5-6 hours",
    bestFor: ["Astrological remedies", "Life balance", "Career growth", "Marriage prospects"],
    rating: 4.7,
    reviews: 234
  },
  {
    id: "shiv-chandra-charcha",
    name: "Shiv Chandra Charcha Kit",
    nameHindi: "शिव चंद्र चर्चा किट",
    description: "Materials for Shiva and Chandra combined worship",
    longDescription: "Shiv Chandra Charcha combines the worship of Lord Shiva with Moon (Chandra) worship. This unique ritual is performed for mental peace, emotional balance, and to strengthen the moon in one's horoscope. Especially beneficial for those going through Chandra Mahadasha.",
    price: 749,
    originalPrice: 949,
    image: "/images/shiv-chandra.jpg",
    category: "jaap",
    itemCount: 20,
    items: [
      "Shivling",
      "Chandra Yantra",
      "White Cloth",
      "White Flowers",
      "Milk (1L)",
      "Rice",
      "Mishri",
      "Kheer Ingredients",
      "Gangajal",
      "Sandalwood Paste",
      "Vibhuti",
      "Bilva Leaves",
      "Agarbatti",
      "Dhoop",
      "Camphor",
      "Diya",
      "Cotton Wicks",
      "Ghee",
      "Coconut",
      "Chandra Stotra Book"
    ],
    duration: "1.5-2 hours",
    bestFor: ["Mental peace", "Emotional balance", "Monday worship", "Chandra dosh remedy"],
    rating: 4.6,
    reviews: 145
  },
  {
    id: "mangal-chandika",
    name: "Mangal Chandika Kit",
    nameHindi: "मंगल चंडिका किट",
    description: "Powerful puja kit for Goddess Chandika worship",
    longDescription: "Mangal Chandika Puja is performed to invoke the fierce form of Goddess Durga for protection against evil forces and enemies. This kit contains all red-colored offerings and special tantric items required for this powerful ritual.",
    price: 999,
    originalPrice: 1299,
    image: "/images/chandika.jpg",
    category: "puja",
    itemCount: 26,
    items: [
      "Durga Murti/Photo",
      "Red Cloth",
      "Red Flowers",
      "Hibiscus Flowers",
      "Sindoor",
      "Kumkum",
      "Alta",
      "Red Bangles",
      "Coconut",
      "Kalash",
      "Mango Leaves",
      "Akshat",
      "Agarbatti",
      "Dhoop",
      "Camphor",
      "Diya",
      "Ghee",
      "Oil",
      "Cotton Wicks",
      "Paan Supari",
      "Cloves",
      "Cardamom",
      "Fruits",
      "Sweets",
      "Moli",
      "Durga Saptashati Book"
    ],
    duration: "2-3 hours",
    bestFor: ["Protection", "Victory over enemies", "Tuesday worship", "Strength"],
    rating: 4.8,
    reviews: 189
  }
]

export function getPujaById(id: string): PujaPackage | undefined {
  return pujaPackages.find((p) => p.id === id)
}

export function getPujasByCategory(category: string): PujaPackage[] {
  return pujaPackages.filter((p) => p.category === category)
}

export function getFeaturedPujas(): PujaPackage[] {
  return pujaPackages.filter((p) => p.featured)
}

export function searchPujas(query: string): PujaPackage[] {
  const lowercaseQuery = query.toLowerCase()
  return pujaPackages.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.nameHindi.includes(query) ||
      p.description.toLowerCase().includes(lowercaseQuery) ||
      p.items.some((item) => item.toLowerCase().includes(lowercaseQuery))
  )
}
